version: "3.8"

services:
    frontend:
        container_name: frontend
        restart: unless-stopped
        build:
            context: ..
            dockerfile: docker/Dockerfile.nginx
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ../:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - internal_frontend

networks:
    internal_frontend:
        driver: bridge
