FROM nginx:latest
RUN apt-get update && apt-get install -y --no-install-recommends openssl
RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -nodes -days 365 -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost" -newkey rsa:2048 -keyout /etc/nginx/ssl/selfsigned.key -out /etc/nginx/ssl/selfsigned.crt
RUN apt-get purge -y openssl && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
