name: Front Workflow
run-name: "Author: ${{ github.actor }}, Branch: ${{ inputs.branch }}"

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: "branch"
        options:
          - "main"
        required: true

jobs:
  prepare:
    name: "Preparing Runtime"
    timeout-minutes: 15
    runs-on: [
      'self-hosted',
      'frontend'
    ]
    env:
      # Passed to overwrite namespace
      BRANCH: ${{ inputs.branch }}
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "${{ inputs.branch }}"
          fetch-depth: 0
          clean: true

      - name: Install dependecies
        run: |
          sudo apt update -y
          sudo apt install -y make

  frontend:
    name: "frontend"
    timeout-minutes: 15
    runs-on: [
      'self-hosted',
      'frontend'
    ]
    needs: ["prepare"]
    env:
      # passed to overwrite namespace
      BRANCH: ${{ inputs.branch }}
    defaults:
      run:
        working-directory: .
    steps:
      - name: frontend Build
        run: |
          CI=true make build

      - name: frontend up
        run: |
          CI=true make up
